config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#login'

  resources :time_and_attendance, path: 'time-and-attendance' do
  	collection do
      get   'holidays' => 'company_holidays#index'
  	end

    member do
      get   'calendar'
    end
  end

  resources :timesheets do
  	member do
  		post	'time-in-time-out' => 'timesheets#time_in_time_out'
  	end
  end

  resources :company_holidays, path: 'time-and-attendance/holidays' do

  end

  resources :shifts_and_schedules, path: 'shifts-and-schedules' do
    member do
      get   'schedules'
      get   'leave-tracker' => 'shifts_and_schedules#leave_tracker'
    end
  end

  resources :leaves do
    
  end

  resources :leave_types do
    
  end

  resources :claims_and_reimbursements, path: 'claims-and-reimbursements' do
    member do
      get   'expenses'
    end

    collection do
      get   'populate-types' => 'claims_and_reimbursements#populate_types'
    end
  end

  resources :claim_types do
    
  end

  resources :reimbursement_types do
    
  end

  resources :expense_categories do
    
  end

  resources :users do
    collection do
      get   'login'
      get   'logout'
    end

    member do
      post  'authorize'
    end
  end
end

app/controllers/claim_types_controller.rb
class ClaimTypesController < ApplicationController
	before_action :authenticate_user!
	before_action :claim_types_list, only: [:index, :destroy]
	before_action :claim_type_mod, only: [:edit, :update, :destroy]

	def index
		respond_to do |format|
			format.html
		end
	end

	def new
		respond_to do |format|
			format.html do
				@claim_type = ClaimType.new
			end
		end
	end

	def create
		respond_to do |format|
			format.html do
				@claim_type = ClaimType.new(claim_type_params)

				if @claim_type.save
					flash[:notice] = 'Claim type has been successfully created'
					redirect_to claim_types_path(luid: params[:luid])
				else
					redirect_to new_claim_type_path(luid: params[:luid])
				end
			end
		end
	end

	def edit
		respond_to do |format|
			format.html
		end
	end

	def update
		respond_to do |format|
			format.html do
				if @claim_type.update_attributes(claim_type_params)
					flash[:notice] = 'Claim type has been successfully updated'
					redirect_to claim_types_path(luid: params[:luid])
				else
					redirect_to edit_claim_type_path(@claim_type, luid: params[:luid])
				end
			end
		end
	end

	def destroy
		respond_to do |format|
			format.js do
				@claim_type.destroy
				flash[:notice] = 'Claim type has been successfully deleted'
			end
		end
	end

	private

		def claim_type_params
			params.require(:claim_type).permit(:claim_type)
		end

		def claim_types_list
			@claim_types = ClaimType.all
		end

		def claim_type_mod
			@claim_type = ClaimType.find(params[:id])
		end
end

app/helpers/claim_types_helper.rb
module ClaimTypesHelper
end

app/views/claim_types/partials/_form.html.erb
<%= form_for @claim_type do |v| %>
  <%= hidden_field_tag :luid, params[:luid] %>

	<div class="box-header with-border">
		<h3 class="box-title">Claim Type Form</h3>
    <div class="box-tools">
      <%= link_to 'Back', claim_types_path(luid: params[:luid]), class: 'btn btn-default' %>
    </div>
	</div>

	<div class="box-body">
		<div class="form-group">
      <%= v.label :claim_type %>

      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-list"></i>
        </div>

        <%= v.text_field :claim_type, class: 'form-control', required: true %>
      </div>
    </div>
	</div>

	<div class="box-footer">
		<div class="pull-right">
			<%= v.submit class: 'btn btn-primary' %>
    </div>
	</div>
<% end %>

app/views/claim_types/partials/_list.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>Claim type</th>
			<th>Added on</th>
			<th>Updated on</th>
			<% if current_user.is_admin %>
				<th>Actions</th>
			<% end %>
		</tr>
	</thead>

	<tbody>
		<% if @claim_types.empty? %>
			<tr>
				<td colspan="6" align="center">No claim types available.</td>
			</tr>
		<% else %>
			<% @claim_types.each do |lt| %>
				<tr>
					<td><%= lt.claim_type %></td>
					<td><%= time_ago_in_words(lt.created_at) %> ago</td>
					<td><%= time_ago_in_words(lt.updated_at) %> ago</td>
					<% if current_user.is_admin %>
						<td>
							<%= link_to edit_claim_type_path(lt, luid: params[:luid]), class: 'btn btn-primary btn-xs' do %>
								<%= content_tag :i, '', :class => 'fa fa-pencil' %> Edit
							<% end %>

							<%= link_to claim_type_path(lt, luid: params[:luid]), class: 'btn btn-danger btn-xs', data: { method: :delete, remote: true, confirm: 'Are you sure you want to delete claim type?' } do %>
								<%= content_tag :i, '', :class => 'fa fa-trash' %> Delete
							<% end %>
						</td>
					<% end %>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>