config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#login'

  resources :time_and_attendance, path: 'time-and-attendance' do
  	collection do
      get   'holidays' => 'company_holidays#index'
  	end

    member do
      get   'calendar'
    end
  end

  resources :timesheets do
  	member do
  		post	'time-in-time-out' => 'timesheets#time_in_time_out'
  	end
  end

  resources :company_holidays, path: 'time-and-attendance/holidays' do

  end

  resources :shifts_and_schedules, path: 'shifts-and-schedules' do
    member do
      get   'schedules'
      get   'leave-tracker' => 'shifts_and_schedules#leave_tracker'
    end
  end

  resources :leaves do
    
  end

  resources :leave_types do
    
  end

  resources :claims_and_reimbursements, path: 'claims-and-reimbursements' do
    member do
      get   'expenses'
    end

    collection do
      get   'populate-types' => 'claims_and_reimbursements#populate_types'
    end
  end

  resources :claim_types do
    
  end

  resources :reimbursement_types do
    
  end

  resources :expense_categories do
    
  end

  resources :users do
    collection do
      get   'login'
      get   'logout'
    end

    member do
      post  'authorize'
    end
  end
end

app/controllers/claims_and_reimbursements_controller.rb
class ClaimsAndReimbursementsController < ApplicationController
	before_action :authenticate_user!

	def index
		respond_to do |format|
			format.html do
				@crs = current_user.is_admin ? ClaimAndReimbursement.all : current_user.claims_and_reimbursements
			end
		end
	end

	def new
		respond_to do |format|
			format.html do
				@claim_and_reimbursement = ClaimAndReimbursement.new
			end
		end
	end

	def create
		respond_to do |format|
			format.html do 
				uri = URI('http://ec2-54-200-53-10.us-west-2.compute.amazonaws.com:8080/asdi/claims_and_reimbursement/file')

				crp = params[:claim_and_reimbursement]

				req = Net::HTTP::Post.new(uri)
				req.body = URI.encode_www_form({
					user_id: params[:luid],
					application_type: crp[:application_type],
					type: crp[:type],
					purpose_of_expense: crp[:purpose_of_expense],
					period_start: crp[:period_start],
					period_end: crp[:period_end],
					expense_date: params[:expense_date],
					description: params[:description],
					category: params[:category],
					cost: params[:cost]
				})

				res = Net::HTTP.start(uri.hostname, uri.port) { |http| http.request(req) }

				resp = JSON.parse(res.body)

				if resp['responseCode'].eql?(200)
					flash[:notice] = "#{crp[:application_type].titleize} has been successfully filed"
					redirect_to claims_and_reimbursements_path(luid: params[:luid])
				else
					flash[:alert] = resp['response']
					redirect_to new_claims_and_reimbursement_path(luid: params[:luid])
				end
			end
		end
	end

	def update
		respond_to do |format|
			format.html do
				uri = URI('http://ec2-54-200-53-10.us-west-2.compute.amazonaws.com:8080/asdi/claims_and_reimbursement/manage')
				cr = ClaimAndReimbursement.find(params[:id])

				req = Net::HTTP::Post.new(uri)
				req.body = URI.encode_www_form({
					cr_id: params[:id],
					status: params[:uaction].upcase
				})

				res = Net::HTTP.start(uri.hostname, uri.port) { |http| http.request(req) }

				resp = JSON.parse(res.body)

				if resp['responseCode'].eql?(200)
					flash[:notice] = "#{cr.application_type.titleize} has been successfully #{params[:uaction].downcase}d"
				else
					flash[:alert] = resp['response']
				end

				redirect_to claims_and_reimbursements_path(luid: params[:luid])
			end
		end
	end

	def expenses
		respond_to do |format|
			format.js do
				claim_and_reimbursement = ClaimAndReimbursement.find(params[:id])
				@expenses = claim_and_reimbursement.expenses
				@total_expenses = claim_and_reimbursement.total_expenses
			end
		end
	end

	def populate_types
		respond_to do |format|
			format.js
		end
	end
end

app/helpers/claims_and_reimbursements_helper.rb
module ClaimsAndReimbursementsHelper
	def populate_types
		types = nil
		types = options_for_select(ClaimType.all.map{ |ct| [ct.claim_type, ct.claim_type]}, nil) if params[:apptype].eql?('Claim')
		types = options_for_select(ReimbursementType.all.map{ |rt| [rt.reimbursement_type, rt.reimbursement_type]}, nil) if params[:apptype].eql?('Reimbursement')

		types
	end
end

app/views/claims_and_reimbursements/partials/_add_item_form_modal.html.erb
<div class="modal fade" id="add-item-modal" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <%= button_tag type: 'button', class: 'close', data: { dismiss: 'modal' }, aria: { label: 'close' } do %>
          <%= content_tag :span, 'x', aria: { hidden: true } %>
        <% end %>
        <h4 class="modal-title">Add item</h4>
      </div>

      <div class="modal-body">
        <div class="form-group">
          <label>Expense Date</label>

          <div class="input-group date">
            <div class="input-group-addon">
              <i class="fa fa-calendar"></i>
            </div>

            <%= text_field_tag 'expense_date', nil, class: 'form-control' %>
          </div>
        </div>
        
        <div class="form-group">
          <label>Category</label>

          <div class="input-group">
            <div class="input-group-addon">
              <i class="fa fa-list"></i>
            </div>
            
            <%= select_tag 'category', options_for_select(ExpenseCategory.all.map{ |ec| [ec.category_name, ec.category_name] }), class: 'form-control' %>
          </div>
        </div>
        
        <div class="form-group">
          <label>Description</label>

          <div class="input-group">
            <div class="input-group-addon">
              <i class="fa fa-align-left"></i>
            </div>

            <%= text_area_tag 'description', '', class: 'form-control', placeholder: 'Expense description', cols: 30, rows: 5 %>
          </div>
        </div>

        <div class="form-group">
          <label>Cost</label>

          <div class="input-group">
            <div class="input-group-addon">
              <i class="fa fa-money"></i>
            </div>

            <%= text_field_tag 'cost', nil, class: 'form-control', placeholder: 'Cost' %>
          </div>
        </div>
      </div>
      
      <div class="modal-footer">
        <%= button_tag 'Close', class: 'btn btn-default pull-left', data: { dismiss: 'modal' } %>
        <%= button_tag 'Add Expense', class: 'btn btn-primary', id: 'create-item-btn', data: { dismiss: 'modal' } %>
      </div>
    </div>
  </div>
</div>

app/views/claims_and_reimbursements/partials/_expenses_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Category</th>
      <th>Description</th>
      <th>Cost</th>
    </tr>
  </thead>

  <tbody>
    <% unless @expenses.nil? %>
      <% if @expenses.empty? %>
        <tr>
          <td colspan="4">No expenses available.</td>
        </tr>
      <% else %>
        <% @expenses.each do |expense| %>
          <tr>
            <td><%= expense.expense_date %></td>
            <td><%= expense.category %></td>
            <td><%= expense.description %></td>
            <td><%= expense.cost %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>

    <tr>
      <td colspan="3"><strong>TOTAL</strong></td>
      <td><u><%= @total_expenses %></u></td>
    </tr>
  </tbody>
</table>

app/views/claims_and_reimbursements/partials/_expenses_modal.html.erb
<div class="modal fade" id="expenses-modal" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <%= button_tag type: 'button', class: 'close', data: { dismiss: 'modal' }, aria: { label: 'close' } do %>
          <%= content_tag :span, 'x', aria: { hidden: true } %>
        <% end %>
        <h4 class="modal-title">Expenses</h4>
      </div>

      <div class="modal-body table-responsive" id="expenses-list">
        <%= render partial: 'claims_and_reimbursements/partials/expenses_list' %>
      </div>
      
      <div class="modal-footer">
        <%= button_tag 'Close', class: 'btn btn-default pull-left', data: { dismiss: 'modal' } %>
      </div>
    </div>
  </div>
</div>

app/views/claims_and_reimbursements/partials/_form.html.erb
<%= form_for @claim_and_reimbursement, url: claims_and_reimbursements_path, html: { id: 'claim-and-reimbursement-form' } do |v| %>
  <div id="hidden-fields">
    <%= hidden_field_tag :user_id, current_user.id %>
    <%= hidden_field_tag :luid, params[:luid] %>
  </div>

  <div class="box-header with-border">
    <h3 class="box-title">Application Form</h3>
    <div class="box-tools">
      <%= link_to 'Back', claims_and_reimbursements_path(luid: params[:luid]), class: 'btn btn-default' %>
    </div>
  </div>

  <div class="box-body">
    <div class="form-group">
      <label>Application Type</label>

      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-list"></i>
        </div>

        <%= select_tag 'claim_and_reimbursement[application_type]', options_for_select(['Claim', 'Reimbursement']), class: 'form-control', id: 'application-type' %>
      </div>
    </div>

    <div class="form-group">
      <label>Type</label>

      <div class="input-group date">
        <div class="input-group-addon">
          <i class="fa fa-list"></i>
        </div>

        <div id="type"></div>
      </div>
    </div>
    
    <div class="form-group">
      <label>Purpose of Expense</label>

      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-align-left"></i>
        </div>

        <%= text_area_tag 'claim_and_reimbursement[purpose_of_expense]', nil, class: 'form-control', placeholder: 'Purpose of Expense', cols: 30, rows: 5 %>
      </div>
    </div>

    <div class="form-group">
      <label>Period Start</label>

      <div class="input-group date">
        <div class="input-group-addon">
          <i class="fa fa-calendar"></i>
        </div>

        <%= text_field_tag 'claim_and_reimbursement[period_start]', nil, class: 'form-control', id: 'period-start' %>
      </div>
    </div>

    <div class="form-group">
      <label>Period End</label>

      <div class="input-group date">
        <div class="input-group-addon">
          <i class="fa fa-calendar"></i>
        </div>      

        <%= text_field_tag 'claim_and_reimbursement[period_end]', nil, class: 'form-control', id: 'period-end' %>
      </div>
    </div>

    <div class="form-group">
      <label>
        Itemized Expenses
        &nbsp;

        <%= link_to '#', id: 'add-item-btn', class: 'btn btn-success btn-xs', data: { toggle: 'tooltip' }, title: 'Add Item' do %>
          <%= content_tag :i, '', class: 'fa fa-plus' %>
        <% end %>
      </label>

      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Date</th>
              <th>Description</th>
              <th>Category</th>
              <th>Cost</th>
              <th></th>
            </tr>
          </thead>

          <tbody id="expenses-list"></tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="box-footer">
    <div class="pull-right">
      <%= submit_tag 'Submit', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<%= render partial: 'claims_and_reimbursements/partials/add_item_form_modal' %>

<script>
  var populate_types_claims_and_reimbursements_path = "<%= j(populate_types_claims_and_reimbursements_path) %>";
  var luid = "<%= j(params[:luid]) %>";
</script>

app/views/claims_and_reimbursements/partials/_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Employee</th>
      <th>Application Type</th>
      <th>Claim/Reimbursement Type</th>
      <th>Purpose</th>
      <th>Date Filed</th>
      <th>Period</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody id="cr-list">
    <% if @crs.empty? %>
      <tr>
        <td colspan="8" align="center">No claims and reimbursements applications available.</td>
      </tr>
    <% else %>
      <% @crs.each do |cr| %>
        <tr>
          <td><%= cr.user.username %> : <%= cr.user.id %></td>
          <td><%= cr.application_type %></td>
          <td><%= cr.cr_type %></td>
          <td><%= cr.purpose_of_expense %></td>
          <td><%= cr.date_filed %></td>
          <td><%= cr.period_start %> - <%= cr.period_end %></td>
          <td class="<%= cr.cr_status.downcase %>"><%= cr.cr_status.upcase %></td>
          <td>
            <% if current_user.is_admin || current_user.eql?(cr.user) %>
              <%= link_to expenses_claims_and_reimbursement_path(cr, luid: params[:luid]), class: 'view-expenses btn btn-info btn-xs', data: { id: cr.id, remote: true } do %>
                <%= content_tag :i, '', class: 'fa fa-list' %> View Expenses
              <% end %>
            <% end %>

            <% if current_user.is_admin && !current_user.eql?(cr.user) && cr.cr_status.eql?('PENDING') %>
              <%= link_to 'Approve', claims_and_reimbursement_path(cr, uaction: 'approve', luid: params[:luid]), class: 'btn btn-success btn-xs', data: { method: :patch, confirm: 'Are you sure you want to approve this file?' } %>
              <%= link_to 'Disapprove', claims_and_reimbursement_path(cr, uaction: 'disapprove', luid: params[:luid]), class: 'btn btn-danger btn-xs', data: { method: :patch, confirm: 'Are you sure you want to disapprove this file?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>