config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#login'

  resources :time_and_attendance, path: 'time-and-attendance' do
  	collection do
      get   'holidays' => 'company_holidays#index'
  	end

    member do
      get   'calendar'
    end
  end

  resources :timesheets do
  	member do
  		post	'time-in-time-out' => 'timesheets#time_in_time_out'
  	end
  end

  resources :company_holidays, path: 'time-and-attendance/holidays' do

  end

  resources :shifts_and_schedules, path: 'shifts-and-schedules' do
    member do
      get   'schedules'
      get   'leave-tracker' => 'shifts_and_schedules#leave_tracker'
    end
  end

  resources :leaves do
    
  end

  resources :leave_types do
    
  end

  resources :claims_and_reimbursements, path: 'claims-and-reimbursements' do
    member do
      get   'expenses'
    end

    collection do
      get   'populate-types' => 'claims_and_reimbursements#populate_types'
    end
  end

  resources :claim_types do
    
  end

  resources :reimbursement_types do
    
  end

  resources :expense_categories do
    
  end

  resources :users do
    collection do
      get   'login'
      get   'logout'
    end

    member do
      post  'authorize'
    end
  end
end

app/models/expense_category.rb
class ExpenseCategory < ApplicationRecord
	self.table_name = 'tbl_expense_categories'

	def category_name=(category_name)
		write_attribute(:category_name, category_name.titleize)
	end
end

app/controllers/expense_categories_controller.rb
class ExpenseCategoriesController < ApplicationController
	before_action :authenticate_user!
	before_action :expense_categories_list, only: [:index, :destroy]
	before_action :expense_category_mod, only: [:edit, :update, :destroy]

	def index
		respond_to do |format|
			format.html
		end
	end

	def new
		respond_to do |format|
			format.html do
				@expense_category = ExpenseCategory.new
			end
		end
	end

	def create
		respond_to do |format|
			format.html do
				@expense_category = ExpenseCategory.new(expense_category_params)

				if @expense_category.save
					flash[:notice] = 'Expense category has been successfully created'
					redirect_to expense_categories_path(luid: params[:luid])
				else
					flash[:alert] = @expense_category.errors.full_messages
					redirect_to new_expense_category_path(luid: params[:luid])
				end
			end
		end
	end

	def edit
		respond_to do |format|
			format.html
		end
	end

	def update
		respond_to do |format|
			format.html do
				if @expense_category.update_attributes(expense_category_params)
					flash[:notice] = 'Expense category has been successfully updated'
					redirect_to expense_categories_path(luid: params[:luid])
				else
					flash[:alert] = @expense_category.errors.full_messages
					redirect_to edit_expense_category_path(@expense_category, luid: params[:luid])
				end
			end
		end
	end

	def destroy
		respond_to do |format|
			format.js do
				@expense_category.destroy
				flash[:notice] = 'Expense category has been successfully deleted'
			end
		end
	end

	private

		def expense_category_params
			params.require(:expense_category).permit(:category_name)
		end

		def expense_categories_list
			@expense_categories = ExpenseCategory.all
		end

		def expense_category_mod
			@expense_category = ExpenseCategory.find(params[:id])
		end
end

app/helpers/expense_categories_helper.rb
module ExpenseCategoriesHelper
end

app/views/expense_categories/partials/_form.html.erb
<%= form_for @expense_category do |v| %>
  <%= hidden_field_tag :luid, params[:luid] %>
  
	<div class="box-header with-border">
		<h3 class="box-title">Expense Category Form</h3>
    <div class="box-tools">
      <%= link_to 'Back', expense_categories_path(luid: params[:luid]), class: 'btn btn-default' %>
    </div>
	</div>

	<div class="box-body">
		<div class="form-group">
      <%= v.label :category_name %>

      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-list"></i>
        </div>

        <%= v.text_field :category_name, class: 'form-control', required: true %>
      </div>
    </div>
	</div>

	<div class="box-footer">
		<div class="pull-right">
			<%= v.submit class: 'btn btn-primary' %>
    </div>
	</div>
<% end %>

app/views/expense_categories/partials/_list.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>Expense Category</th>
			<th>Added on</th>
			<th>Updated on</th>
			<% if current_user.is_admin %>
				<th>Actions</th>
			<% end %>
		</tr>
	</thead>

	<tbody>
		<% if @expense_categories.empty? %>
			<tr>
				<td colspan="6" align="center">No expense categories available.</td>
			</tr>
		<% else %>
			<% @expense_categories.each do |lt| %>
				<tr>
					<td><%= lt.category_name %></td>
					<td><%= time_ago_in_words(lt.created_at) %> ago</td>
					<td><%= time_ago_in_words(lt.updated_at) %> ago</td>
					<% if current_user.is_admin %>
						<td>
							<%= link_to edit_expense_category_path(lt, luid: params[:luid]), class: 'btn btn-primary btn-xs' do %>
								<%= content_tag :i, '', :class => 'fa fa-pencil' %> Edit
							<% end %>

							<%= link_to expense_category_path(lt, luid: params[:luid]), class: 'btn btn-danger btn-xs', data: { method: :delete, remote: true, confirm: 'Are you sure you want to delete expense category?' } do %>
								<%= content_tag :i, '', :class => 'fa fa-trash' %> Delete
							<% end %>
						</td>
					<% end %>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>