config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#login'

  resources :time_and_attendance, path: 'time-and-attendance' do
  	collection do
      get   'holidays' => 'company_holidays#index'
  	end

    member do
      get   'calendar'
    end
  end

  resources :timesheets do
  	member do
  		post	'time-in-time-out' => 'timesheets#time_in_time_out'
  	end
  end

  resources :company_holidays, path: 'time-and-attendance/holidays' do

  end

  resources :shifts_and_schedules, path: 'shifts-and-schedules' do
    member do
      get   'schedules'
      get   'leave-tracker' => 'shifts_and_schedules#leave_tracker'
    end
  end

  resources :leaves do
    
  end

  resources :leave_types do
    
  end

  resources :claims_and_reimbursements, path: 'claims-and-reimbursements' do
    member do
      get   'expenses'
    end

    collection do
      get   'populate-types' => 'claims_and_reimbursements#populate_types'
    end
  end

  resources :claim_types do
    
  end

  resources :reimbursement_types do
    
  end

  resources :expense_categories do
    
  end

  resources :users do
    collection do
      get   'login'
      get   'logout'
    end

    member do
      post  'authorize'
    end
  end
end

app/controllers/shifts_and_schedules_controller.rb
class ShiftsAndSchedulesController < ApplicationController
	before_action :authenticate_user!
	before_action :user_mod, only: [:edit, :update, :show, :leave_tracker, :schedules]

	def index
		respond_to do |format|
			format.html
		end
	end

	def show
		respond_to do |format|
			format.html
		end
	end

	def edit
		respond_to do |format| 
			format.html do
				@schedules = current_user.schedules
			end
		end
	end

	def update
		respond_to do |format|
			format.html do
				uri = URI('http://ec2-54-200-53-10.us-west-2.compute.amazonaws.com:8080/asdi/shifts_and_schedules/file')

				req = Net::HTTP::Post.new(uri)

				reqbody = {
					id: @user.id,
					schedules: params[:schedules],
					times: params[:times]	
				}

				i = 0

				while 1 do
					break if params["days#{i}".to_sym].nil?

					reqbody["day#{i}".to_sym] = params["days#{i}".to_sym]

					i += 1
				end

				req.body = URI.encode(reqbody.map{ |k, v| "#{k}=#{v}" }.join("&"))

				res = Net::HTTP.start(uri.hostname, uri.port) { |http| http.request(req) }

				resp = JSON.parse(res.body)

				if resp['status'].downcase.eql?('success')
					flash[:notice] = "#{@user.username}'s schedules has been successfully updated"
					redirect_to shifts_and_schedule_path(@user, luid: params[:luid])
				else
					flash[:alert] = 'Schedule required.'
					redirect_to edit_shifts_and_schedule_path(@user, luid: params[:luid])
				end
			end
		end
	end

	def schedules
		respond_to do |format|
			format.json do
				scheds = Array.new

				@user.schedules.each do |schedule|
					scheds << {
						id: schedule.id,
						start_date: schedule.start_date,
						end_date: schedule.end_date,
						start_time: schedule.start_time,
						end_time: schedule.end_time,
						days: schedule.days,
					}
				end

				render json: { schedules: scheds }
			end
		end
	end

	def leave_tracker
		respond_to do |format|
			format.html do
				@leaves = @user.leaves
			end
		end
	end

	private

		def user_mod
			@user = User.find(params[:id])
		end
end

app/helpers/shifts_and_schedules_helper.rb
module ShiftsAndSchedulesHelper
end

app/views/shifts_and_schedules/edit.html.erb
<section class="content-header">
  <div class="alert-message">
    <%= render partial: 'partials/alert_message' %>
  </div>

  <h1>
    <i class="fa fa-clock-o"></i> Shifts and Schedules Management
  </h1>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box">
				<%= render partial: 'shifts_and_schedules/partials/form' %>
			</div>
		</div>
	</div>
</section>

app/views/shifts_and_schedules/leave_tracker.html.erb
<section class="content-header">
  <h1>
    <i class="fa fa-clock-o"></i> Shifts and Schedules Management
  </h1>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Leave Tracker</h3>

					<div class="box-tools">
						<%= link_to 'Remaining Leaves', '#', class: 'btn btn-primary', id: 'remaining-leaves-btn', data: { id: params[:id] } %>
						<%= link_to 'Back', users_path(luid: params[:luid]), class: 'btn btn-default' %>
			    </div>
				</div>

				<div class="box-body table-responsive">
					<%= render partial: 'shifts_and_schedules/leave_tracker/partials/list' %>
				</div>
			</div>
		</div>
	</div>
</section>

<%= render partial: 'shifts_and_schedules/leave_tracker/partials/remaining_leaves_modal' %>

app/views/shifts_and_schedules/show.html.erb
<section class="content-header">
  <div class="alert-message">
    <%= render partial: 'partials/alert_message' %>
  </div>
  
  <h1>
    <i class="fa fa-clock-o"></i> Shifts and Schedules Management
  </h1>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box">
				<div class="box-header with-border">
					<h3 class="box-title">My Shifts and Schedules</h3>
					<div class="box-tools">
						<%= link_to 'Manage Shifts and Schedules', edit_shifts_and_schedule_path(@user, luid: params[:luid]), class: 'btn btn-primary' if current_user.is_admin %>
						<%= link_to 'Back', users_path(luid: params[:luid]), class: 'btn btn-default' %>
			    </div>
				</div>

				<div class="box-body">
					<%= render partial: 'shifts_and_schedules/partials/list' %>
				</div>
			</div>
		</div>
	</div>
</section>